<a href="https://colab.research.google.com/github/ihyaulumuddin044/Pengantar_ML/blob/main/modules/multiple_linear_regression/multiple_linear_regression_from_scratch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

# Regresi linier berganda
Mengapa Regresi Linier Berganda?
Regresi linier sederhana mencoba memprediksi satu variabel dependen (Y) berdasarkan satu variabel independen (X). Tapi dalam kenyataannya, banyak hal dipengaruhi oleh lebih dari satu faktor. Di sinilah regresi linier berganda masuk. Ia memungkinkan kita memprediksi variabel dependen berdasarkan dua atau lebih variabel independen.

Contoh: Kita ingin memprediksi harga rumah. Harga rumah tidak hanya ditentukan oleh luasnya, tapi juga jumlah kamar tidur, lokasi, fasilitas terdekat, dan lain-lain.



In [2]:
# Membuat data fiktif
data = {
    'Jam_Belajar': [2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2],
    'Kehadiran_Kelas': [8, 9, 7, 10, 8, 9, 10, 9, 8, 7, 8, 9, 10, 7, 8, 9, 10, 9, 6, 7],
    'Nilai_Ujian': [60, 65, 70, 75, 80, 85, 90, 92, 95, 55, 60, 68, 73, 78, 82, 88, 93, 96, 50, 58]
}

df = pd.DataFrame(data)
print("Dataset:\n", df.head())

Dataset:
    Jam_Belajar  Kehadiran_Kelas  Nilai_Ujian
0            2                8           60
1            3                9           65
2            4                7           70
3            5               10           75
4            6                8           80


## Membangun Matriks X dan Vektor Y (NumPy)

In [3]:
# Variabel dependen/target (Y)
Y = df['Nilai_Ujian'].values.reshape(-1,1)
# print("Variabel Dependen (Y):\n", Y)
# print("Variabel Dependen (Y):\n", Y.shape)

# Variabel independen (X)
X_raw = df[['Kehadiran_Kelas','Jam_Belajar']].values
# print("Variabel Independen (X):\n", X)
# print("Variabel Independen (X):\n", X.shape)

# Menambahkan kolom konstanta (intercept) ke matriks X
# np.ones((X_raw.shape[0], 1)) membuat kolom berisi angka 1 dengan jumlah baris yang sama dengan X_raw
X = np.concatenate((np.ones((X_raw.shape[0], 1)), X_raw), axis=1)

print("\nMatriks X dengan kolom konstanta (5 baris pertama):\n", X[0:5])
print("\nVektor Y (5 baris pertama):\n", Y[0:5])


Matriks X dengan kolom konstanta (5 baris pertama):
 [[ 1.  8.  2.]
 [ 1.  9.  3.]
 [ 1.  7.  4.]
 [ 1. 10.  5.]
 [ 1.  8.  6.]]

Vektor Y (5 baris pertama):
 [[60]
 [65]
 [70]
 [75]
 [80]]


## Menghitung Koefisien Regresi (β) (NumPy)

Sekarang kita akan menerapkan rumus OLS: β

In [4]:
# Menghitung (X^T X)
XTX = np.dot(X.T, X)
print("Matriks X^T X:\n", XTX)

# Invers dari XTX
XTX_inv= np.linalg.inv(XTX)
print("\nInvers dari Matriks X^T X:\n", XTX_inv)

# Menghitung (X^T Y)
XTY = np.dot(X.T, Y)
print("\nMatriks X^T Y:\n", XTY)

# Menghitung koefisien beta
betas = np.dot(XTX_inv, XTY)

print("\nKoefisien Regresi (beta):\n", betas)

# Ekstrak nilai koefisien
intercept = betas[0][0]
coef_jam_belajar = betas[1][0]
coef_kehadiran_kelas = betas[2][0]

print(f"\nIntercept (beta_0): {intercept:.2f}")
print(f"Koefisien Jam Belajar (beta_1): {coef_jam_belajar:.2f}")
print(f"Koefisien Kehadiran Kelas (beta_2): {coef_kehadiran_kelas:.2f}")

Matriks X^T X:
 [[  20.  168.  111.]
 [ 168. 1438.  967.]
 [ 111.  967.  773.]]

Invers dari Matriks X^T X:
 [[ 2.93252135 -0.37431458  0.04715696]
 [-0.37431458  0.05215845 -0.01149845]
 [ 0.04715696 -0.01149845  0.00890632]]

Matriks X^T Y:
 [[ 1513.]
 [12899.]
 [ 9179.]]

Koefisien Regresi (beta):
 [[41.47475989]
 [ 0.90960752]
 [ 4.78099764]]

Intercept (beta_0): 41.47
Koefisien Jam Belajar (beta_1): 0.91
Koefisien Kehadiran Kelas (beta_2): 4.78


## Setelah kita mendapatkan koefisien, kita bisa menggunakannya untuk memprediksi nilai ujian baru.

In [5]:
# Contoh prediksi:
# Misal seorang siswa belajar 6 jam dan memiliki kehadiran kelas 9
jam_belajar_baru = 6
kehadiran_kelas_baru = 9

# Buat vektor fitur untuk prediksi (jangan lupa konstanta 1)
data_baru = np.array([1, jam_belajar_baru, kehadiran_kelas_baru])
print(data_baru)

# Hitung prediksi
prediksi_nilai = np.dot(data_baru, betas)

print(f"\nPrediksi Nilai Ujian untuk 6 jam belajar dan 9 kehadiran kelas: {prediksi_nilai[0]:.2f}")

[1 6 9]

Prediksi Nilai Ujian untuk 6 jam belajar dan 9 kehadiran kelas: 89.96


## Evaluasi Model (Optional, tapi Penting)

In [6]:
# Prediksi nilai untuk data yang ada
Y_pred = np.dot(X, betas)

# Menghitung Total Sum of Squares (SST)
# SST = sum((Y_i - Y_mean)^2)
Y_mean = np.mean(Y)
SST = np.sum((Y - Y_mean)**2)

# Menghitung Residual Sum of Squares (SSR)
# SSR = sum((Y_i - Y_pred_i)^2)
SSR = np.sum((Y - Y_pred)**2)

# Menghitung R-squared
R_squared = 1 - (SSR / SST)

print(f"\nR-squared: {R_squared:.4f}")


R-squared: 0.9864


## Dengan menggunkan Fungsi

In [7]:
import pandas as pd
import numpy as np

def linear_regression_predict(X_train, y_train, X_new):
    """
    Melakukan regresi linier berganda dan membuat prediksi.

    Args:
        X_train (np.ndarray atau pd.DataFrame): Variabel independen untuk training,
                                                 tanpa kolom konstanta (intercept).
        y_train (np.ndarray atau pd.Series): Variabel dependen untuk training.
        X_new (np.ndarray atau pd.DataFrame): Variabel independen untuk prediksi,
                                                tanpa kolom konstanta.

    Returns:
        tuple: (betas, predictions)
               betas (np.ndarray): Koefisien regresi, termasuk intercept.
               predictions (np.ndarray): Prediksi nilai untuk X_new.
    """
    # Pastikan y_train adalah kolom vektor
    if isinstance(y_train, pd.Series):
        y_train = y_train.values.reshape(-1, 1)
    elif isinstance(y_train, np.ndarray) and y_train.ndim == 1:
        y_train = y_train.reshape(-1, 1)

    # Pastikan X_train adalah numpy array
    if isinstance(X_train, pd.DataFrame):
        X_train = X_train.values
    if isinstance(X_new, pd.DataFrame):
        X_new = X_new.values

    # Tambahkan kolom konstanta (intercept) ke X_train
    X_train_biased = np.concatenate((np.ones((X_train.shape[0], 1)), X_train), axis=1)

    # Hitung koefisien beta menggunakan rumus OLS
    try:
        XTX = np.dot(X_train_biased.T, X_train_biased)
        XTX_inv = np.linalg.inv(XTX)
        XTY = np.dot(X_train_biased.T, y_train)
        betas = np.dot(XTX_inv, XTY)
    except np.linalg.LinAlgError:
        print("Peringatan: Matriks tidak dapat di-inverse. Mungkin ada multikolinearitas.")
        return None, None # Atau tangani error dengan cara lain

    # Tambahkan kolom konstanta ke X_new untuk prediksi
    X_new_biased = np.concatenate((np.ones((X_new.shape[0], 1)), X_new), axis=1)

    # Buat prediksi
    predictions = np.dot(X_new_biased, betas)

    return betas, predictions

# --- Contoh Penggunaan Fungsi ---
# Data fiktif seperti sebelumnya
data = {
    'Jam_Belajar': [2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2],
    'Kehadiran_Kelas': [8, 9, 7, 10, 8, 9, 10, 9, 8, 7, 8, 9, 10, 7, 8, 9, 10, 9, 6, 7],
    'Nilai_Ujian': [60, 65, 70, 75, 80, 85, 90, 92, 95, 55, 60, 68, 73, 78, 82, 88, 93, 96, 50, 58]
}
df = pd.DataFrame(data)

# Siapkan data training
X_train_data = df[['Jam_Belajar', 'Kehadiran_Kelas']]
y_train_data = df['Nilai_Ujian']

# Data baru untuk prediksi
X_predict_data = pd.DataFrame({
    'Jam_Belajar': [6, 7.5, 3],
    'Kehadiran_Kelas': [9, 8, 7]
})

# Panggil fungsi
betas_func, predictions_func = linear_regression_predict(X_train_data, y_train_data, X_predict_data)

if betas_func is not None:
    print("\n--- Penggunaan sebagai Fungsi ---")
    print("Koefisien Regresi (Intercept, Jam_Belajar, Kehadiran_Kelas):\n", betas_func.flatten())
    print("Prediksi untuk data baru:\n", predictions_func.flatten())

    # Interpretasi
    print(f"\nInterpretasi:")
    print(f"Intercept: {betas_func[0][0]:.2f}")
    print(f"Koefisien Jam Belajar: {betas_func[1][0]:.2f}")
    print(f"Koefisien Kehadiran Kelas: {betas_func[2][0]:.2f}")


--- Penggunaan sebagai Fungsi ---
Koefisien Regresi (Intercept, Jam_Belajar, Kehadiran_Kelas):
 [41.47475989  4.78099764  0.90960752]
Prediksi untuk data baru:
 [78.34721345 84.60910239 62.18500548]

Interpretasi:
Intercept: 41.47
Koefisien Jam Belajar: 4.78
Koefisien Kehadiran Kelas: 0.91


In [8]:
invers_matrix = pd.DataFrame({
    "A": [1,2,3]
    ,"B": [4,5,1]
    ,"C": [7,8,2]
})

transposed_matrix = invers_matrix.transpose()
print(transposed_matrix)

invers_matrix_np = np.linalg.inv(invers_matrix)
print(invers_matrix_np)


   0  1  2
A  1  2  3
B  4  5  1
C  7  8  2
[[-0.22222222  0.11111111  0.33333333]
 [-2.22222222  2.11111111 -0.66666667]
 [ 1.44444444 -1.22222222  0.33333333]]


### catatatn hal-hal penting

* mencari nilai B1 (koifisien/slope)
* mencari nilai B0(Intercept)
* perkalian matrik dengan matrik
* transpose  matrik
* invers matrik


